import type { ResultRow, ScreenProps } from '../types';
import { color, font, sar, tier as tierColor } from '../tokens';
import { Button, ConnectionBanner, Eyebrow, Header, Money, Panel } from '../components/atoms';
import { useDerived } from '../useDerived';

export default function ResultsScreen({ state, actions, myId }: ScreenProps) {
  const d = useDerived(state, myId); const rows = state.results ?? []; const shown = rows.slice(Math.max(0, rows.length - state.revealedCount));
  return <div style={{ maxWidth: 680, margin: '0 auto', padding: '20px 16px 60px' }}><Header code={state.code} isHost={d.isHost} /><ConnectionBanner connection={state.connection} /><div style={{ textAlign: 'center', marginBottom: 22 }}><Eyebrow>النتيجة — {state.theme?.titleAr}</Eyebrow>{d.fullyRevealed && rows[0] && <h1 style={{ fontFamily: font.display, fontWeight: 900, fontSize: 'clamp(30px, 8vw, 46px)', lineHeight: 1.15, margin: '10px 0 0', color: color.brassSoft, animation: 'rise 500ms ease both' }}>فاز {rows[0].name}</h1>}</div><div style={{ display: 'grid', gap: 12 }}>{shown.map((r) => <ResultCard key={r.playerId} row={r} isMe={r.playerId === myId} hideMarket={false} />)}</div>{d.isHost ? <div style={{ marginTop: 26, textAlign: 'center' }}>{!d.fullyRevealed ? <Button variant="primary" onClick={actions.revealNext} style={{ minWidth: 200 }}>اكشف التالي</Button> : <Button variant="primary" onClick={actions.newRound} style={{ minWidth: 200 }}>جولة جديدة</Button>}</div> : !d.fullyRevealed && <p style={{ marginTop: 24, textAlign: 'center', fontFamily: font.body, fontSize: 13, color: color.mute }}>المدير يكشف الترتيب واحد واحد…</p>}</div>;
}

function ResultCard({ row, isMe, hideMarket }: { row: ResultRow; isMe: boolean; hideMarket: boolean }) {
  const first = row.rank === 1;
  return <div style={{ animation: 'rise 450ms ease both' }}><Panel surface={first ? 'lot' : 'inset'} style={{ padding: 15, borderColor: first ? color.brass : undefined, borderWidth: first ? 2 : 1 }}><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 11 }}><span style={{ fontFamily: font.num, fontSize: 22, fontWeight: 600, color: first ? color.brass : color.mute, width: 30, flex: '0 0 auto' }}>{row.rank}</span><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: font.body, fontSize: 17, fontWeight: 700, color: color.text }}>{row.name}{isMe && <span style={{ color: color.brass, fontSize: 13, marginInlineStart: 6 }}>أنت</span>}</div><div style={{ fontFamily: font.body, fontSize: 12, color: color.mute, marginTop: 2 }}>مصروف <Money muted>{sar(row.spentSar)}</Money> · باقي <Money muted>{sar(row.leftSar)}</Money></div></div><div style={{ textAlign: 'center', flex: '0 0 auto' }}><div style={{ fontFamily: font.num, fontSize: 30, fontWeight: 600, lineHeight: 1, fontVariantNumeric: 'tabular-nums', color: first ? color.brass : color.text }}>{row.score100}</div><div style={{ fontFamily: font.body, fontSize: 10, color: color.mute, marginTop: 3 }}>من ١٠٠</div></div></div><div style={{ height: 6, background: color.ink, borderRadius: 3, overflow: 'hidden' }}><div style={{ height: '100%', width: `${row.score100}%`, background: first ? color.brass : color.mute, transition: 'width .8s ease' }} /></div><div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 13 }}>{row.garage.map((c, i) => <span key={i} style={{ background: color.panel, borderInlineStart: `3px solid ${tierColor[c.tier]}`, borderRadius: 4, padding: '7px 10px', fontFamily: font.body, fontSize: 12, color: color.text }}>{c.nameAr} <Money style={{ fontSize: 11 }}>{sar(c.paidSar)}</Money>{!hideMarket && <Money muted style={{ fontSize: 11 }}> / {sar(c.marketPriceSar)}</Money>}</span>)}</div>{row.breakdown && row.breakdown.length > 0 && <div style={{ marginTop: 12, paddingTop: 10, borderTop: `1px solid ${color.line}`, display: 'flex', flexWrap: 'wrap', gap: 10 }}>{row.breakdown.map((b, i) => <span key={i} style={{ fontFamily: font.body, fontSize: 12, color: color.mute }}>{b.voterName} <Money muted style={{ fontSize: 12 }}>{b.score}</Money></span>)}</div>}</Panel></div>;
}
